language: java
jdk:
  - openjdk8
before_install:
  - wget -P /tmp https://services.gradle.org/distributions/gradle-6.9.4-bin.zip
  - unzip -qq /tmp/gradle-6.9.4-bin.zip -d /tmp
  - export GRADLE_HOME=/tmp/gradle-6.9.4
  - export PATH=$GRADLE_HOME/bin:$PATH
