language: java
jdk:
  - openjdk8
before_install:
  - wget https://services.gradle.org/distributions/gradle-6.9.4-bin.zip
  - unzip -qq gradle-6.9.4-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.9.4
  - export PATH=$GRADLE_HOME/bin:$PATH
